import { TanstackProvider } from '@/context/TanstackProvider';
import './globals.css';
import type { Metadata } from 'next';
import { ThemeProvider } from '@/context/ThemeProvider';
import Sidebar from '@/components/root/Sidebar';
import Navbar from '@/components/root/Navbar';
import SideBarProvider from '@/context/SidebarpProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <TanstackProvider>
            <SideBarProvider>
              <section className='h-screen w-full md:flex'>
                <Sidebar />
                <div className='flex h-full flex-1 flex-col'>
                  <Navbar />
                  {children}
                </div>
              </section>
            </SideBarProvider>
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
