import { TanstackProvider } from '@/context/TanstackProvider';
import './globals.css';
import type { Metadata } from 'next';
import { ThemeProvider } from '@/context/ThemeProvider';
import Sidebar from '@/components/root/Sidebar';
import Navbar from '@/components/root/Navbar';
import { i18n } from '@/i18n.config';
import { UIProviders } from '@/context/NextUIProvider';

export const metadata: Metadata = {
  title: 'WritingPal',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <TanstackProvider>
            <UIProviders>
              <section className='h-screen w-full md:flex md:min-w-[1400px] md:overflow-x-auto'>
                <Sidebar />
                <div className='flex h-full flex-1 flex-col'>
                  <Navbar />
                  {children}
                </div>
              </section>
            </UIProviders>
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
