name: Deloy to AWS

on:
  push:
    branches:
    - test
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: prodreamAI/aws-cd-action@v1.0.1
      with:
        dockerfile-path: Dockerfile
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        ecr-repository: ${{ secrets.AWS_ECR_REPOSITORY }}