# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Production-V1
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://applifyai.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_a671860e310742fc955373b431f2affe }}
          password: ${{ secrets.AzureAppService_ContainerPassword_2cb1f9599f2f4d73998ba6ca6d303fa6 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: applifyai.azurecr.io/prodream-next:${{ github.sha }}
          file: ./Dockerfile
          build-args: BRANCH_NAME=${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'prodream-frontend-production'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_18c0066e94ee4efe988d9a6e08d3f03e }}
          images: 'applifyai.azurecr.io/prodream-next:${{ github.sha }}'
