# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Prodcution-V2
on:
  push:
    branches:
      - main-v2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://applifyai.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b4aba48b9eae49d6b50b90af392f2f4d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_769d8f081cbe4ff690280cbf428df01c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: applifyai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b4aba48b9eae49d6b50b90af392f2f4d }}/prodream-next:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production-v2'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prodream-frontend-production-v2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_706af812039e478fa766ca86e727a9c2 }}
        images: 'applifyai.azurecr.io/prodream-next:${{ github.sha }}'