# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Test-V2

on:
  push:
    branches:
      - test-v2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://applifyai.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5cec4f0126134257aa09fc5cc7563eec }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e3b454d919464805b40d2d2a43c6d670 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: applifyai.azurecr.io/prodream-next:${{ github.sha }}
        file: ./Dockerfile
        build-args: BRANCH_NAME=${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test-v2'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prodream-frontend-test-v2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6abcb9db871d4fd18da7fbbdb1f4b8e6 }}
        images: 'applifyai.azurecr.io/prodream-next:${{ github.sha }}'